[versions]
# Build
agp = "9.0.1"
kotlin = "2.3.20"
ksp = "2.3.4"
core-ktx = "1.17.0"

# Compose
compose-bom = "2026.03.00"
compose-activity = "1.12.4"
compose-lifecycle = "2.10.0"
uiText = "1.10.6"
#foundationLayout = "1.10.6"

# Navigation3 (类型安全)
navigation-compose = "2.8.9"

# Koin (依赖注入 4.x)
koin = "4.2.0"
koin-plugin = "0.4.1"

# hilt
hilt = "2.59.2"

# Network
retrofit = "2.12.0"
okhttp = "4.12.0"
gson = "2.12.0"

# Database
room = "2.7.2"

# Coroutines
coroutines = "1.10.2"

# Serialization
kotlinx-serialization = "1.7.3"

# Image
coil = "3.1.0"

# Permissions (2026 新)
accompanist = "0.36.0"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"





[libraries]
# AndroidX Core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "compose-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-lifecycle" }


# Compose BOM
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }

# Navigation3
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }

# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Accompanist
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
#android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Hilt 插件 (注意：新版 Hilt 推荐直接在 module 中用 id，或者在这里定义)
# 如果在这里定义，ID 是 com.google.dagger.hilt.android
#hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
#kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-plugin" } # 编译器插件是导致增量编译失效的元凶,除非n 的 @Single/@Factory 注解（而不是 DSL），否则不需要编译器。
#parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }



[bundles]
compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-material3",
    "androidx-compose-material-icons-extended"
]
koin = [
    "koin-core",
    "koin-android",
    "koin-compose",
    "koin-compose-viewmodel"
]
network = [
    "retrofit",
    "retrofit-converter-gson",
    "okhttp-logging"
]
room = [
    "room-runtime",
    "room-ktx"
]
coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]